version: "3.7"
services:
  webapp:
    build: .
    volumes:
      - ./frontend/dist:/root/frontend/dist
    ports:
      - "80:8080"
    networks:
      - redis_network
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge